version: '3.7'

services:

  development:
    image: quentinlcs/rust-dev-environment
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/home/vscode/.ssh:cached # Give access to ssh keys on the host
      - target:/workspace/target # Set target as a volume for performance. 
    environment:
      - GIT_NAME=quentin
      - GIT_EMAIL=quentin.lechasles@gmail.com
      - DATABASE_URL=postgres://app_user:dev_only_password@database/app_db
    # depends_on:
    #   - database
    command: sleep infinity # Overrides default command so things don't shut down after the process ends.
  
  # database:
  #   image: postgres:16-alpine
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U app_user"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3

# networks:
#   default:
#     driver: bridge

volumes:
  target:
