version: '3.7'

services:

  development:
    image: quentinlcs/rust-dev-environment
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/usr/vscode/.ssh:cached # Give access to ssh keys on the host
      - /var/run/docker.sock:/var/run/docker.sock # We need this so docker in docker works
      - target:/workspace/target # Set target as a volume for performance. 
    # depends_on:
    #   - database
    command: sleep infinity # Overrides default command so things don't shut down after the process ends.
  
  # database:
  #   image: postgres:16-alpine
  #   environment:
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_USER: user
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U vscode"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3

volumes:
  target:
